import { useEffect, useState } from 'react';
import { useWedding } from '../context/WeddingContext';
import { Calendar, Clock, MapPin, Sparkles, Shirt } from 'lucide-react';

interface TimeLeft {
  days: number;
  hours: number;
  minutes: number;
  seconds: number;
}

export default function InvitationHome() {
  const { settings } = useWedding();
  const [timeLeft, setTimeLeft] = useState<TimeLeft>({ days: 0, hours: 0, minutes: 0, seconds: 0 });

  // Calculate countdown time left
  useEffect(() => {
    const targetDate = new Date(`${settings.date}T${settings.time}:00`);

    const interval = setInterval(() => {
      const now = new Date();
      const difference = targetDate.getTime() - now.getTime();

      if (difference <= 0) {
        clearInterval(interval);
        setTimeLeft({ days: 0, hours: 0, minutes: 0, seconds: 0 });
      } else {
        const d = Math.floor(difference / (1000 * 60 * 60 * 24));
        const h = Math.floor((difference / (1000 * 60 * 60)) % 24);
        const m = Math.floor((difference / 1000 / 60) % 60);
        const s = Math.floor((difference / 1000) % 60);
        setTimeLeft({ days: d, hours: h, minutes: m, seconds: s });
      }
    }, 1000);

    return () => clearInterval(interval);
  }, [settings.date, settings.time]);

  // Format date in Brazilian Portuguese: "22 de Maio de 2027"
  const formatDatePT = (dateStr: string) => {
    const parts = dateStr.split('-');
    if (parts.length !== 3) return dateStr;
    const months = [
      'Janeiro', 'Fevereiro', 'Março', 'Abril', 'Maio', 'Junho',
      'Julho', 'Agosto', 'Setembro', 'Outubro', 'Novembro', 'Dezembro'
    ];
    const day = parseInt(parts[2], 10);
    const month = months[parseInt(parts[1], 10) - 1];
    const year = parts[0];
    return `${day} de ${month} de ${year}`;
  };

  // Image path generated by the tool
  const heroImageUrl = "/src/assets/images/wedding_hero_banner_1783131957950.jpg";

  return (
    <div className="bg-[#FAF9F5] min-h-screen text-gray-800 animate-fade-in pb-16">
      {/* 1. Hero Section */}
      <div className="relative h-[90vh] flex items-center justify-center overflow-hidden">
        {/* Background photo with parallax feel */}
        <div className="absolute inset-0 z-0">
          <img
            src={heroImageUrl}
            alt="Casamento Henderson e Alana Banner"
            className="w-full h-full object-cover scale-105 select-none transition-transform duration-1000 hover:scale-100"
            referrerPolicy="no-referrer"
          />
          {/* Elegant Dark and Cream Gradients */}
          <div className="absolute inset-0 bg-gradient-to-t from-[#FAF9F5] via-black/30 to-black/40" />
        </div>

        {/* Hero content overlays */}
        <div className="relative z-10 text-center px-4 max-w-4xl flex flex-col items-center">
          <span className="text-white/90 text-sm sm:text-base font-sans tracking-[0.35em] uppercase font-light mb-3">
            Salvem esta Data
          </span>

          <h1 className="font-cursive text-7xl sm:text-9xl text-gold-100 drop-shadow-lg leading-none py-4 select-none">
            {settings.coupleName1} & {settings.coupleName2}
          </h1>

          <div className="h-[1px] w-32 bg-gold-200/60 my-6" />

          <p className="font-serif italic text-white/90 text-xl sm:text-2xl tracking-wide max-w-2xl">
            "Com a bênção de Deus e de nossos pais, convidamos você para celebrar o nosso amor."
          </p>

          {/* Micro Card holding time details */}
          <div className="mt-8 bg-white/10 backdrop-blur-md border border-white/20 px-6 py-3 rounded-full text-white font-sans text-xs sm:text-sm tracking-[0.2em] uppercase flex items-center gap-3">
            <Calendar size={14} className="text-gold-200" />
            <span>{formatDatePT(settings.date)}</span>
            <span className="text-gold-200/50">|</span>
            <Clock size={14} className="text-gold-200" />
            <span>{settings.time}h</span>
          </div>
        </div>
      </div>

      {/* 2. Interactive Countdown Widget */}
      <div className="relative z-10 -mt-16 max-w-4xl mx-auto px-4">
        <div className="bg-white border border-gold-200/50 rounded-2xl shadow-xl p-6 sm:p-10 flex flex-col md:flex-row items-center justify-between gap-6 md:gap-4">
          <div className="text-center md:text-left">
            <div className="text-[10px] uppercase tracking-widest text-gold-600 font-semibold mb-1 flex items-center justify-center md:justify-start gap-1">
              <Sparkles size={12} />
              Contagem Regressiva
            </div>
            <h3 className="font-serif text-2xl text-gray-800 font-medium">O grande dia está chegando...</h3>
          </div>

          {/* Time digits */}
          <div className="flex gap-4 sm:gap-8 justify-center">
            {[
              { label: 'Dias', value: timeLeft.days },
              { label: 'Horas', value: timeLeft.hours },
              { label: 'Minutos', value: timeLeft.minutes },
              { label: 'Segundos', value: timeLeft.seconds }
            ].map((unit, index) => (
              <div key={index} className="flex flex-col items-center">
                <div className="w-16 h-16 sm:w-20 sm:h-20 bg-gold-50/50 border border-gold-200/30 rounded-xl flex items-center justify-center shadow-inner">
                  <span className="font-serif text-2xl sm:text-3xl font-semibold text-gold-600">
                    {String(unit.value).padStart(2, '0')}
                  </span>
                </div>
                <span className="text-[10px] uppercase tracking-widest text-gray-500 font-medium mt-1.5">
                  {unit.label}
                </span>
              </div>
            ))}
          </div>
        </div>
      </div>

      {/* 3. Welcome Quote & Card Details */}
      <div className="max-w-4xl mx-auto px-4 mt-20 text-center">
        <span className="font-cursive text-5xl text-gold-500 block mb-3">Bem-vindos ao nosso site</span>
        <h2 className="font-serif text-3xl sm:text-4xl tracking-wide text-gray-800 mb-6 font-medium">
          Henderson & Alana
        </h2>
        <p className="font-sans text-gray-600 leading-relaxed text-base max-w-2xl mx-auto">
          {settings.storyText}
        </p>
      </div>

      {/* 4. Ceremony vs Reception Cards */}
      <div className="max-w-6xl mx-auto px-4 mt-24 grid md:grid-cols-2 gap-8 lg:gap-12">
        {/* Card 1: Ceremony */}
        <div className="bg-white border border-gold-100 rounded-2xl shadow-lg p-8 hover:shadow-xl transition-shadow flex flex-col h-full group">
          <div className="w-12 h-12 rounded-full bg-gold-50 border border-gold-200/30 flex items-center justify-center mb-6 text-gold-500 group-hover:bg-gold-500 group-hover:text-white transition-all">
            <Sparkles size={20} />
          </div>

          <span className="text-[10px] uppercase tracking-widest text-gold-600 font-bold mb-1">
            Momento Sagrado
          </span>
          <h3 className="font-serif text-2xl font-semibold text-gray-800 mb-4">A Cerimônia</h3>

          <p className="text-gray-600 text-sm leading-relaxed mb-6 flex-grow">
            Daremos o nosso "sim" na deslumbrante Catedral de Fortaleza. Uma arquitetura majestosa para abençoar o nosso compromisso eterno.
          </p>

          <div className="space-y-3 pt-4 border-t border-gold-50 text-xs sm:text-sm text-gray-700">
            <div className="flex items-start gap-2.5">
              <Calendar size={16} className="text-gold-500 mt-0.5 flex-shrink-0" />
              <span>Sábado, 22 de Maio de 2027</span>
            </div>
            <div className="flex items-start gap-2.5">
              <Clock size={16} className="text-gold-500 mt-0.5 flex-shrink-0" />
              <span>Início às 16:00 horas (Pedimos pontualidade)</span>
            </div>
            <div className="flex items-start gap-2.5">
              <MapPin size={16} className="text-gold-500 mt-0.5 flex-shrink-0" />
              <span className="italic">{settings.ceremonyLocation}</span>
            </div>
          </div>

          {/* Embedded Google Map */}
          <div className="mt-6 rounded-xl overflow-hidden border border-gray-100 h-48 bg-gray-50">
            <iframe
              src={settings.ceremonyMapUrl}
              className="w-full h-full border-0"
              allowFullScreen={false}
              loading="lazy"
              referrerPolicy="no-referrer"
              title="Cerimônia Map"
            />
          </div>
        </div>

        {/* Card 2: Reception / Party */}
        <div className="bg-white border border-gold-100 rounded-2xl shadow-lg p-8 hover:shadow-xl transition-shadow flex flex-col h-full group">
          <div className="w-12 h-12 rounded-full bg-gold-50 border border-gold-200/30 flex items-center justify-center mb-6 text-gold-500 group-hover:bg-gold-500 group-hover:text-white transition-all">
            <Sparkles size={20} className="fill-current" />
          </div>

          <span className="text-[10px] uppercase tracking-widest text-gold-600 font-bold mb-1">
            Celebrar e Brindar
          </span>
          <h3 className="font-serif text-2xl font-semibold text-gray-800 mb-4">A Recepção & Festa</h3>

          <p className="text-gray-600 text-sm leading-relaxed mb-6 flex-grow">
            Após a cerimônia, nos reuniremos para brindar, comer bem e dançar até o amanhecer no Espaço Jardins Premium. Um local cercado de natureza exuberante.
          </p>

          <div className="space-y-3 pt-4 border-t border-gold-50 text-xs sm:text-sm text-gray-700">
            <div className="flex items-start gap-2.5">
              <Calendar size={16} className="text-gold-500 mt-0.5 flex-shrink-0" />
              <span>Sábado, 22 de Maio de 2027</span>
            </div>
            <div className="flex items-start gap-2.5">
              <Clock size={16} className="text-gold-500 mt-0.5 flex-shrink-0" />
              <span>Logo após a Cerimônia Religiosa (A partir de 18:00h)</span>
            </div>
            <div className="flex items-start gap-2.5">
              <MapPin size={16} className="text-gold-500 mt-0.5 flex-shrink-0" />
              <span className="italic">{settings.receptionLocation}</span>
            </div>
          </div>

          {/* Embedded Google Map */}
          <div className="mt-6 rounded-xl overflow-hidden border border-gray-100 h-48 bg-gray-50">
            <iframe
              src={settings.receptionMapUrl}
              className="w-full h-full border-0"
              allowFullScreen={false}
              loading="lazy"
              referrerPolicy="no-referrer"
              title="Festa Map"
            />
          </div>
        </div>
      </div>

      {/* 5. Dress Code Section */}
      <div className="max-w-4xl mx-auto px-4 mt-24">
        <div className="bg-gradient-to-br from-gold-50/70 to-gold-100/30 border border-gold-200/40 rounded-2xl p-8 shadow-md flex flex-col md:flex-row items-center gap-8">
          <div className="w-16 h-16 rounded-full bg-white flex items-center justify-center text-gold-600 shadow-sm flex-shrink-0">
            <Shirt size={28} />
          </div>

          <div className="text-center md:text-left flex-grow">
            <h4 className="font-serif text-2xl font-semibold text-gray-800 mb-2">Código de Vestimenta (Dress Code)</h4>
            <p className="font-sans text-sm text-gold-800 font-semibold mb-3 tracking-wide uppercase">
              Traje: Esporte Fino / Passeio Completo
            </p>
            <p className="text-gray-600 text-sm leading-relaxed">
              <strong>Para elas:</strong> Vestidos midi ou longos fluidos. Convidamos as madrinhas a usar tons de rose e pastel, mas todas as cores são bem-vindas (exceto branco, off-white ou preto).<br />
              <strong>Para eles:</strong> Costume social de linho ou alfaiataria em cores claras ou escuras. O uso de gravata é opcional.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}
